name: Build API

on: 
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  api: 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - uses: wshihadeh/docker-deployment-action@v1
      name: Docker-Compose Remote Deployment
      with:
        remote_docker_host: ${{ secrets.SSH_USER }}@septotrip.com
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.prod.yml
        copy_stack_file: 'false'
        deploy_path: /var/lib/docker-deploy
        deployment_mode: docker-compose
        pull_images_first: 'true'
        args: --env-file /var/lib/docker-deploy/.env up -d api
        pre_deployment_command_args: 'down api'
