name: Test api

env:
  NODE_ENV: test
  JWT_SECRET_KEY: notimportanttoken
  POSTGRES_HOST: ${{ secrets.TEST_POSTGRES_HOST }}
  POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
  POSTGRES_PORT: ${{ secrets.TEST_POSTGRES_PORT }}
  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

on:
  pull_request: 
    branches: [ master, tg/adding-tests ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dépendencies
      run: yarn install
    - name: Test
      run: yarn test
